### PR TITLE
Adjust timing

### PR DESCRIPTION
**Pull request by dekrypted**
GD Comments have a ratelimit of 1 per 15 seconds, so you should set it to 15500 seconds interval (15 seconds plus a half second for safety)

### CODE REVIEW

**Comment by doxyf** [comment]
The rate limit is only client side in the Geometry Dash game client, not in the servers. However it very often gives internal server error no matter how many seconds you wait before posting next comment.

**Comment by dekrypted** [comment]
I've found that about 25 seconds is the best time. EVery ~6 requests you get a 500 but despite the slower speeds its still more efficient in the long run compared to a 10-15 second cooldown which returns a 500 every 1-2 requests.

**Comment by doxyf** [comment]
Alright then, I'll change the default timing to 25 seconds

**Comment by doxyf** [comment]
Still it doesn't matter since it's just default configuration

**Pull request closed without merging**
